"""empty message

Revision ID: 1ee5011de8f0
Revises: fb8f8654a103
Create Date: 2023-02-17 23:57:28.197681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ee5011de8f0'
down_revision = 'fb8f8654a103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               nullable=True)
        batch_op.create_unique_constraint(None, ['location'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('location',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
