"""empty message

Revision ID: 262af6420438
Revises: f90052f2ce35
Create Date: 2023-03-21 20:49:17.684001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '262af6420438'
down_revision = 'f90052f2ce35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
