"""empty message

Revision ID: 979784d4b587
Revises: af78c9dc7ed6
Create Date: 2023-03-04 01:28:08.830157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '979784d4b587'
down_revision = 'af78c9dc7ed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
