"""empty message

Revision ID: f0ed019aa2e4
Revises: 03ada0955ca2
Create Date: 2023-02-14 23:01:57.337250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0ed019aa2e4'
down_revision = '03ada0955ca2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('profile_pic', sa.String(length=120), nullable=True),
    sa.Column('groups_location', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=120), nullable=True),
    sa.Column('interests', sa.String(length=120), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('groups_activity_type', sa.String(length=120), nullable=True),
    sa.Column('groups_guidelines', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id', 'groups_location'),
    sa.UniqueConstraint('gender'),
    sa.UniqueConstraint('interests')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('location', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('interests', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('sexual_interests', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('is_online', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('current_plan', sa.String(length=120), nullable=True))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['interests'])
        batch_op.create_unique_constraint(None, ['gender'])
        batch_op.create_unique_constraint(None, ['sexual_interests'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('current_plan')
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_online')
        batch_op.drop_column('sexual_interests')
        batch_op.drop_column('interests')
        batch_op.drop_column('gender')
        batch_op.drop_column('location')
        batch_op.drop_column('profile_pic')

    op.drop_table('groups')
    # ### end Alembic commands ###
