"""empty message

Revision ID: f90052f2ce35
Revises: e0015b5e6a86
Create Date: 2023-03-21 20:33:55.975778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f90052f2ce35'
down_revision = 'e0015b5e6a86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('randnum',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('randnum',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
